bike/urls.py
from django.urls import path
from . import views

app_name = 'bike'

urlpatterns = [
    path('bicycles/', views.product_list, name='product_list'),
    path('accessories/', views.accessories_product_list, name='accessories_product_list'),
    path('parts/', views.parts_product_list, name='parts_product_list'),
    path('<slug:category_slug>/', views.product_list,
         name='product_list_by_category'),
    path('single/<int:id>/<slug:slug>/', views.product_details,
         name='product_detail'),
]

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('create/', views.order_create, name='order_create'),
]

web/urls.py
from django.contrib import admin
from django.urls import path, include
from main import IndexView, ErrorView, AccessoriesView, SingleView, CartView, PartsView, BicyclesView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('', IndexView.as_view()),
    path('index/', IndexView.as_view()),
    path('404/', ErrorView.as_view()),
    path('orders/', include('orders.urls', namespace='orders')),
    path('', include("bike.urls", namespace='accessories')),
    path('', include('bike.urls', namespace='parts')),
    path('', include('bike.urls', namespace='bicycles')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

bike/models.py
from django.db import models
from django.urls import reverse


class Category(models.Model):
    ordering = ('name',)
    name = models.CharField(max_length=20, db_index=True)
    slug = models.SlugField(max_length=20, unique=True)

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('bike:product_list_by_category', args=[self.slug])


class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    name = models.CharField(max_length=100, db_index=True)
    slug = models.SlugField(max_length=100,db_index=True, unique=True)
    image = models.ImageField(upload_to="static/images/", blank=True)
    description = models.TextField(max_length=100, blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)

    class Meta:
        ordering = ('name',)
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'
        index_together = (('id', 'slug'), )

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('bike:product_details', args=[self.id, self.slug])

cart/models.py
from django.db import models

# Create your models here.

orders/models.py
from django.db import models
from bike.models import Product


class Order(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.EmailField()
    address = models.CharField(max_length=250)
    postal_code = models.CharField(max_length=20)
    city = models.CharField(max_length=100)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    paid = models.BooleanField(default=False)

    class Meta:
        ordering = ('-created',)
        verbose_name = 'Заказ'
        verbose_name_plural = 'Заказы'

    def __str__(self):
        return f'Order {self.id}'

    def get_total_cost(self):
        return sum(item.get_cost() for item in self.items.all())


class OrderItem(models.Model):
    order = models.ForeignKey(Order, related_name='items', on_delete=models.CASCADE)
    product = models.ForeignKey(Product, related_name='order_items', on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return '{}'.format(self.id)

    def get_cost(self):
        return self.price * self.quantity

cart/forms.py
from django import forms


PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    quantity = forms.IntegerField(max_value=99, min_value=1)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

orders/forms.py
from django import forms
from .models import Order


class OrderCreateForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['first_name', 'last_name', 'email', 'address', 'postal_code', 'city']

bike/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Product
from cart.forms import CartAddProductForm


def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.all()
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    return render(request, 'bicycles.html', {'category': category, 'categories': categories, 'products': products})


def accessories_product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.all()
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    return render(request, 'accessories.html', {'category': category, 'categories': categories, 'products': products})


def parts_product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.all()
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    return render(request, 'parts.html', {'category': category, 'categories': categories, 'products': products})


def product_details(request, id, slug):
    product = get_object_or_404(Product, id=id, slug=slug)
    cart_product_form = CartAddProductForm()
    return render(request, 'single.html', {'product': product, 'cart_product_form': cart_product_form})

cart/views.py
from django.shortcuts import render
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from bike.models import Product
from .cart import Cart
from .forms import CartAddProductForm


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, quantity=cd['quantity'], update_quantity=cd['update'])
    return redirect('cart:cart_detail')


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'], 'update': True})
    return render(request, 'cart.html', {'cart': cart})

orders/views.py
from django.shortcuts import render
from .models import OrderItem
from .forms import OrderCreateForm
from cart.cart import Cart


def order_create(request):
    cart = Cart(request)
    if request.method == 'POST':
        form = OrderCreateForm(request.POST)
        if form.is_valid():
            order = form.save()
            for item in cart:
                OrderItem.objects.create(order=order,
                                         product=item['product'],
                                         price=item['price'],
                                         quantity=item['quantity'])
            # clear the cart
            cart.clear()
            return render(request, 'thankyou.html', {'order': order})
    else:
        form = OrderCreateForm()
    return render(request, 'order-create.html', {'cart': cart, 'form': form})

templates/base-shop.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
<title>Bike Shop a Ecommerce Category Flat Bootstarp Responsive Website Template| Parts :: w3layouts</title>
<link href="/static/css/bootstrap.css" rel='stylesheet' type='text/css' />
<!-- jQuery (Bootstrap's JavaScript plugins) -->
<script src="/static/js/jquery.min.js"></script>
<!-- Custom Theme files -->
<link href="/static/css/form.css" rel="stylesheet" type="text/css" media="all" />
<link href="/static/css/style.css" rel="stylesheet" type="text/css" media="all" />
<!-- Custom Theme files -->
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="keywords" content="Bike-shop Responsive web template, Bootstrap Web Templates, Flat Web Templates, Andriod Compatible web template,
Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyErricsson, Motorola web design" />
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
<!--webfont-->
<link href='http://fonts.googleapis.com/css?family=Roboto:500,900,100,300,700,400' rel='stylesheet' type='text/css'>
<!--webfont-->
<!-- dropdown -->
<script src="/static/js/jquery.easydropdown.js"></script>
<link href="/static/css/nav.css" rel="stylesheet" type="text/css" media="all"/>
<script src="/static/js/scripts.js" type="text/javascript"></script>
<!--js-->

</head>
<body>
<!--banner-->
<script src="/static/js/responsiveslides.min.js"></script>
<script>
    $(function () {
      $("#slider").responsiveSlides({
      	auto: false,
      	nav: true,
      	speed: 500,
        namespace: "callbacks",
        pager: true,
      });
    });
  </script>
<div class="banner-bg banner-sec">
	  <div class="container">
			 <div class="header">
			       <div class="logo">
						 <a href="/index/">
                             <img src="/static/images/logo.png" alt=""/>
                         </a>
				   </div>
				  <div class="top-nav">
						<label class="mobile_menu" for="mobile_menu">
						<span>Menu</span>
						</label>
						<input id="mobile_menu" type="checkbox">
					   <ul class="nav">
						  <li class="dropdown1"><a href="/bicycles/">BICYCLES</a>
							  <ul class="dropdown2">
									<li><a href="/bicycles/">FIXED / SINGLE SPEED</a></li>
									<li><a href="/bicycles/">CITY BIKES</a></li>
									<li><a href="/bicycles/">PREMIMUN SERIES</a></li>
							  </ul>
						  </li>
						  <li class="dropdown1"><a href="/parts/">PARTS</a>
							 <ul class="dropdown2">
									<li><a href="/parts/">CHAINS</a></li>
									<li><a href="/parts/">TUBES</a></li>
									<li><a href="/parts/">TIRES</a></li>
									<li><a href="/parts/">DISC BREAKS</a></li>
							  </ul>
						 </li>
						 <li class="dropdown1"><a href="/accessories/">ACCESSORIES</a>
							 <ul class="dropdown2">
									<li><a href="/accessories/">LOCKS</a></li>
										<li><a href="/accessories/">HELMETS</a></li>
										<li><a href="/accessories/">ARM COVERS</a></li>
										<li><a href="/accessories/">JERSEYS</a></li>
							  </ul>
						 </li>
						 <li class="dropdown1"><a href="/404/">EXTRAS</a>
							 <ul class="dropdown2">
									<li><a href="/404/">CLASSIC BELL</a></li>
									<li><a href="/404/">BOTTLE CAGE</a></li>
									<li><a href="/404/">TRUCK GRIP</a></li>
							  </ul>
						 </li>
						  <a class="shop" href="/cart/">
                              <img src="/static/images/cart.png" alt=""/>
                          </a>
					  </ul>
				 </div>
				 <div class="clearfix"></div>
			 </div>
	  </div>
</div>
<!--/banner-->
         {% block content %}

         {% endblock %}

<div class="footer">
	 <div class="container wrap">
		<div class="logo2">
			 <a href="/index/"><img src="/static/images/logo2.png" alt=""/></a>
		</div>
		<div class="ftr-menu">
			 <ul>
				 <li><a href="/bicycles/">BICYCLES</a></li>
				 <li><a href="/parts/">PARTS</a></li>
				 <li><a href="/accessories/">ACCESSORIES</a></li>
				 <li><a href="/404/">EXTRAS</a></li>
			 </ul>
		</div>
		<div class="clearfix"></div>
	 </div>
</div>
<!---->

</body>
</html>

templates/base.html
{% load static %}
<!--
Author: W3layouts
Author URL: http://w3layouts.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
<!DOCTYPE html>
<html>
<head>
<title>Bike Shop a Ecommerce Category Flat Bootstarp Responsive Website Template| Home :: w3layouts</title>
<link href="../static/css/bootstrap.css" rel='stylesheet' type='text/css' />
<!-- jQuery (Bootstrap's JavaScript plugins) -->
<script src="../static/js/jquery.min.js"></script>
<!-- Custom Theme files -->
<link href="../static/css/style.css" rel="stylesheet" type="text/css" media="all" />
<!-- Custom Theme files -->
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="keywords" content="Bike-shop Responsive web template, Bootstrap Web Templates, Flat Web Templates, Andriod Compatible web template,
Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyErricsson, Motorola web design" />
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
<!--webfont-->
<link href='http://fonts.googleapis.com/css?family=Roboto:500,900,100,300,700,400' rel='stylesheet' type='text/css'>
<!--webfont-->
<!-- dropdown -->
<script src="../static/js/jquery.easydropdown.js"></script>
<link href="../static/css/nav.css" rel="stylesheet" type="text/css" media="all"/>
<script src="../static/js/scripts.js" type="text/javascript"></script>
<!--js-->
<!---- start-smoth-scrolling---->
		<script type="text/javascript" src="../static/js/move-top.js"></script>
		<script type="text/javascript" src="../static/js/easing.js"></script>
		<script type="text/javascript">
			jQuery(document).ready(function($) {
				$(".scroll").click(function(event){
					event.preventDefault();
					$('html,body').animate({scrollTop:$(this.hash).offset().top},900);
				});
			});
		</script>
<!---- start-smoth-scrolling---->


</head>
<body>
<!--banner-->
<script src="../static/js/responsiveslides.min.js"></script>
<script>
    $(function () {
      $("#slider").responsiveSlides({
      	auto: true,
      	nav: true,
      	speed: 500,
        namespace: "callbacks",
        pager: true,
      });
    });
  </script>
<div class="banner-bg banner-bg1">
	  <div class="container">
			 <div class="header">
			       <div class="logo">
						 <a href="/index/">
                             <img src="../static/images/logo.png" alt=""/>
                         </a>
				   </div>
				  <div class="top-nav">
						<label class="mobile_menu" for="mobile_menu">
						<span>Menu</span>
						</label>
						<input id="mobile_menu" type="checkbox">
					   <ul class="nav">
						  <li class="dropdown1"><a href="/bicycles/">BICYCLES</a>
							  <ul class="dropdown2">
									<li><a href="/bicycles/">FIXED / SINGLE SPEED</a></li>
									<li><a href="/bicycles/">CITY BIKES</a></li>
									<li><a href="/bicycles/">PREMIMUN SERIES</a></li>
							  </ul>
						  </li>
						  <li class="dropdown1"><a href="/parts/">PARTS</a>
							 <ul class="dropdown2">
									<li><a href="/parts/">CHAINS</a></li>
									<li><a href="/parts/">TUBES</a></li>
									<li><a href="/parts/">TIRES</a></li>
									<li><a href="/parts/">DISC BREAKS</a></li>
							  </ul>
						 </li>
						 <li class="dropdown1"><a href="/accessories/">ACCESSORIES</a>
							 <ul class="dropdown2">
									<li><a href="/accessories/">LOCKS</a></li>
										<li><a href="/accessories/">HELMETS</a></li>
										<li><a href="/accessories/">ARM COVERS</a></li>
										<li><a href="/accessories/">JERSEYS</a></li>
							  </ul>
						 </li>
						 <li class="dropdown1"><a href="/404/">EXTRAS</a>
							 <ul class="dropdown2">
									<li><a href="/404/">CLASSIC BELL</a></li>
									<li><a href="/404/">BOTTLE CAGE</a></li>
									<li><a href="/404/">TRUCK GRIP</a></li>
							  </ul>
						 </li>
						  <a class="shop" href="/cart/">
                              <img src="/static/images/cart.png" alt=""/>
                              {% with total_items=cart|length %}
                                  {% if cart|length > 0 %}
                              <a>{{ total_items }}</a>
                                  {% endif %}
                              {% endwith %}
                          </a>
					  </ul>
				 </div>
				 <div class="clearfix"></div>
			 </div>
	  </div>
</div>
<!--/banner-->

    {% block content %}
    {% endblock %}

<div class="footer">
	 <div class="container wrap">
		<div class="logo2">
			 <a href="/index/"><img src="/static/images/logo2.png" alt=""/></a>
		</div>
		<div class="ftr-menu">
			 <ul>
				 <li><a href="/bicycles/">BICYCLES</a></li>
				 <li><a href="/parts/">PARTS</a></li>
				 <li><a href="/accessories/">ACCESSORIES</a></li>
				 <li><a href="/404/">EXTRAS</a></li>
			 </ul>
		</div>
		<div class="clearfix"></div>
	 </div>
</div>
<!---->

</body>
</html>

templates/cart.html
<{% extends 'base-shop.html' %}
{%block content%}

<div class="cart">
	 <div class="container">
		 <div class="cart-top">
			<a href="/index/"><< home</a>
		 </div>

		 <div class="col-md-9 cart-items">
			 <h2>My Shopping Bag ({{ cart|length }})</h2>

             {% for item in cart %}
                 {% with product=item.product %}
                     <script>$(document).ready(function(c) {
					$('.{{ product.id }}').on('click', function(c){
						$('.{{ product.id }}').fadeOut('slow', function(c){
							$('.{{ product.id }}').remove();
						});
						});
					});
			   </script>
			 <div class="cart-header {{ product.id }}">
				 <div class="close1 {{ product.id }}">
                 <form action="{% url "cart:cart_remove" product.id %}"
                                                  method="post">
                                                <input type="submit" class="btn btn-primary height-auto btn-sm"
                                                       value="X">
                                                {% csrf_token %}
                                            </form>
                 </div>
				 <div class="cart-sec">
						<div class="cart-item cyc">
							 <img src="{{product.image.url}}"/>
						</div>
					   <div class="cart-item-info">
							 <h3>{{ product.name}}<span>{{ product.name}}</span></h3>
							 <h4><span>Rs. $ </span>{{ product.price }}</h4>
							 <p class="qty">Qty ::</p>
							 <input min="1" type="number" id="quantity" name="quantity" value="{{ item.quantity }}" class="form-control input-small">
					   </div>
					   <div class="clearfix"></div>
						<div class="delivery">
							 <p>Service Charges:: Rs.100.00</p>
							 <span>Delivered in 2-3 business days</span>
							 <div class="clearfix"></div>
				        </div>
				  </div>
			 </div>
		     {% endwith %}
             {% endfor %}
         </div>

		 <div class="col-md-3 cart-total">
			 <a class="continue" href="#">Continue to basket</a>
			 <div class="price-details">
				 <h3>Price Details</h3>
				 <span>Total</span>
				 <span class="total">{{ cart.get_total_price}}</span>
				 <span>Discount</span>
				 <span class="total">---</span>
				 <span>Delivery Charges</span>
				 <span class="total">150.00</span>
				 <div class="clearfix"></div>
			 </div>
			 <h4 class="last-price">TOTAL</h4>
			 <span class="total final">{{ cart.get_total_price }}+150</span>
			 <div class="clearfix"></div>
			 <a class="order" href="{% url "orders:order_create" %}">Place Order</a>
			 <div class="total-item">
				 <h3>OPTIONS</h3>
				 <h4>COUPONS</h4>
				 <a class="cpns" href="#">Apply Coupons</a>
				 <p><a href="#">Log In</a> to use accounts - linked coupons</p>
			 </div>
			</div>
	 </div>
</div>
<!---->
{% endblock %}

templates/order-create.html
{% extends 'base-shop.html' %}

{% block content %}

    <h1>Checkout</h1>
    <div class="order-info">
        <h3>Your order</h3>
        <ul>
            {% for item in cart %}
                <li>
                    {{ item.quantity }}x {{ item.product.name }}
                    <span>${{ item.total_price }}</span>
                </li>
            {% endfor %}
        </ul>
        <p>Total: ${{ cart.get_total_price }}</p>
    </div>
    <form action="." method="post" class="order-form">
        {{ form.as_p }}
        <p><input type="submit" value="Place order"></p>
        {% csrf_token %}
    </form>

{% endblock %}

templates/single.html
{% extends 'base-shop.html' %}
{% load static %}


{%block content%}
<!--/banner-->
<div class="product">
	 <div class="container">
		 <div class="ctnt-bar cntnt">
			 <div class="content-bar">
				 <div class="single-page">
					 <div class="product-head">
						<a href="/index/">Home</a> <span>::</span>
						</div>
					 <!--Include the Etalage files-->
						<link rel="stylesheet" href="/static/css/etalage.css">
						<script src="/static/js/jquery.etalage.min.js"></script>
				<script>
			jQuery(document).ready(function($){

				$('#etalage').etalage({
					thumb_image_width: 400,
					thumb_image_height: 400,
					source_image_width: 800,
					source_image_height: 1000,
					show_hint: true,
					click_callback: function(image_anchor, instance_id){
						alert('Callback example:\nYou clicked on an image with the anchor: "'+image_anchor+'"\n(in Etalage instance: "'+instance_id+'")');
					}
				});

			});
		</script>
						<!--//details-product-slider-->
					 <div class="details-left-slider">
						 <div class="grid images_3_of_2">
						  <ul id="etalage">
							<li>
								<a href="optionallink.html">
									<img class="etalage_thumb_image" src="{{product.image.url}}" class="img-responsive" alt="" />
									<img class="etalage_source_image" src="{{product.image.url}}" class="img-responsive" alt="" />
								</a>
							</li>
							<li>
								<img class="etalage_thumb_image" src="{{product.image.url}}" class="img-responsive" alt=""/>
								<img class="etalage_source_image" src="{{product.image.url}}" class="img-responsive" alt="" />
							</li>
							<li>
								<img class="etalage_thumb_image" src="{{product.image.url}}" class="img-responsive" alt="" />
								<img class="etalage_source_image" src="{{product.image.url}}"class="img-responsive" alt="" />
							</li>
						    <li>
								<img class="etalage_thumb_image" src="{{product.image.url}}" class="img-responsive" alt="" />
								<img class="etalage_source_image" src="{{product.image.url}}"class="img-responsive"  alt="" />
							</li>
						</ul>
						</div>
					 </div>
					 <div class="details-left-info">
							<h3>{{ product.name}}</h3>
								<h4>{{ product.name}}</h4>
							<h4></h4>
							<p><label>$</label> {{ product.price }} <a href="#">Click for offer</a></p>
							<p class="size">SIZE ::</p>
							<a class="length" href="#">XS</a>
							<a class="length" href="#">M</a>
							<a class="length" href="#">S</a>
							<div class="btn_form">
								<a href="/cart/">buy now</a>
								<a href="/cart/">Add to cart</a>
                            <form action="{% url "cart:cart_add" product.id %}" method="post">
                                {{ cart_product_form }}
                                {% csrf_token %}
                                <input type="submit" value="В корзину">
                            </form>
							</div>
							<div class="bike-type">
							<p>TYPE  ::<a href="#">MOUNTAIN BIKE</a></p>
							<p>BRAND  ::<a href="#">SPORTS SCOTTY</a></p>
							</div>
							<h5>Description  ::</h5>
							<p class="desc">The first mechanically-propelled, two-wheeled vehicle may have been built by Kirkpatrick MacMillan, a Scottish blacksmith, in 1839, although the claim is often disputed. He is also associated with the first recorded instance of a cycling traffic offense, when a Glasgow newspaper in 1842 reported an accident in which an anonymous "gentleman from Dumfries-shire... bestride a velocipede... of ingenious design" knocked over a little girl in Glasgow and was fined five
							The word bicycle first appeared in English print in The Daily News in 1868, to describe "Bysicles and trysicles" on the "Champs Elysées and Bois de Boulogne.</p>
					 </div>
					 <div class="clearfix"></div>
				  </div>
			  </div>
		  </div>
		  <div class="single-bottom2">
			  <h6>Related Products</h6>
			 <div class="product">
					 <div class="product-desc">
						  <div class="product-img product-img2">
							 <img src="/static/images/s1.jpg" class="img-responsive " alt=""/>
						 </div>
						 <div class="prod1-desc">
								<h5><a class="product_link" href="/bicycles/">Road Bike</a></h5>
								<p class="product_descr"> Vivamus ante lorem, eleifend nec interdum non, ullamcorper et arcu. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.eleifend nec interdum non, ullamcorper et arcu. Class aptent taciti sociosqu ad litora torquent per conubia nostra. </p>
						 </div>
						 <div class="clearfix"></div>
					 </div>
					 <div class="product_price">
							<span class="price-access">$300.51</span>
							<a class="button1" href="/cart/"><span>Add to cart</span></a>
					 </div>
						<div class="clearfix"></div>
			 </div>
			 <div class="product">
					 <div class="product-desc">
						  <div class="product-img product-img2">
							 <img src="/static/images/s2.jpg" class="img-responsive " alt=""/>
						 </div>
						 <div class="prod1-desc">
								<h5><a class="product_link" href="bicycles.html">Mountain Bike</a></h5>
								<p class="product_descr"> Vivamus ante lorem, eleifend nec interdum non, ullamcorper et arcu. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.eleifend nec interdum non, ullamcorper et arcu. Class aptent taciti sociosqu ad litora torquent per conubia nostra. </p>
						 </div>
						 <div class="clearfix"></div>
					 </div>
					 <div class="product_price">
							<span class="price-access">$1500.51</span>
							<a class="button1" href="/cart/"><span>Add to cart</span></a>
					 </div>
				  <div class="clearfix"></div>
			 </div>
			 <div class="product">
					 <div class="product-desc">
						  <div class="product-img product-img2">
							 <img src="/static/images/s3.jpg" class="img-responsive " alt=""/>
						 </div>
						 <div class="prod1-desc">
								<h5><a class="product_link" href="bicycles.html">Single Speed Bike</a></h5>
								<p class="product_descr"> Vivamus ante lorem, eleifend nec interdum non, ullamcorper et arcu. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.eleifend nec interdum non, ullamcorper et arcu. Class aptent taciti sociosqu ad litora torquent per conubia nostra. </p>
						 </div>
						 <div class="clearfix"></div>
					 </div>
					 <div class="product_price">
							<span class="price-access">$800.51</span>
							<a class="button1" href="/cart/"><span>Add to cart</span></a>
					 </div>
				 <div class="clearfix"></div>
			  </div>
		 </div>
	 </div>
</div>
<!---->
{% endblock %}